### ISSUE TITLE
Relacionar comprobantes con números de comprobantes C31 Sigep

### ISSUE THREAD

**Issue by grovervelasquez** [kplian/sis_contabilidad#20]
Crear una interfaz para agrupar uno o más comprobantes, manuales o automáticos del PXP con un número de comprobante del sistema Sigep.

En la versión actual el agrupador se llama entrega y en la central no se puede finalizar la entrega si no tiene C31 y no se genera el cheque de los comprobantes asociados si no se finaliza la entrega.

En el caso de las regionales validan el comprobante y se genera el cheque pero la relación con una entrega debe hacerse para sacar un resumen de gastos y sea completado el c31 en la central al momento de su revisión y registro en el sigep.

Al registrar el numero en la entrega este se copia en la cabecera de los comprobantes asociados tanto de pago como devengado.

El agrupador permite generar el reporte consolidado por clase de gasto, categoría programática y partida de todos los comprobantes asociados a la entrega para su posterior registro en el Sigep.

**Comment by rensi4rn** [comment]
SE creo la interface de entregas
![image](https://cloud.githubusercontent.com/assets/2071383/21275119/b21ae500-c3a1-11e6-9e8b-9447ad98bfc7.png)
