### ISSUE TITLE
Funcionalidad para registrar facturas mediante QR

### ISSUE THREAD

**Issue by grovervelasquez** [kplian/sis_contabilidad#21]
Actualmente el sistema de contabilidad cuenta con una opción para transcribir facturas por compras de forma manual. Con la nueva normativa de impuestos el uso del codigo QR en las facturas es cada vez mas frecuente.

A partir de código QR y con la ayuda de un lector de códigos de barras se puede facilitar el registro de facturas en el sistema ERP, optimizando tiempos y empleando el mismo en actividades más productivas.

Sugiero que en la pantalla actual se adicione un campo de texto "Contenido QR" que permita copiar la cadena de texto separada por Pipeline que contiene el código QR de las facturas.

![image](https://cloud.githubusercontent.com/assets/18399403/15217615/591f572e-182a-11e6-8ef9-6bee4cc3044f.png)

A partir de esta cadena se puede completar automáticamente los campos Fecha, nit, nro autorizacion, numero de factura, importe total, código de control, importe exento y otros

![image](https://cloud.githubusercontent.com/assets/18399403/15217770/0a2b5a86-182b-11e6-87da-242fdec5914f.png)

Adicionalmente se podría desarrollar una aplicación para dispositivos móviles que permita leer con el celular el código y guardarlo en la base de datos del ERP sin depender de un equipo de escritorio

**Comment by rensi4rn** [comment]
Es buena idea podriamos verlo con Favio,

**Comment by rensi4rn** [comment]
hecho
