### ISSUE TITLE
Plantillas de comprobantes manuales

### ISSUE THREAD

**Issue by grovervelasquez** [kplian/sis_contabilidad#22]
Al ver cómo registrar comprobantes manuales en el sistema TANGO pude evidenciar lo facil que es para el usuario final elaborar un comprobante manual.

Este sistema permite crear plantillas de comprobantes donde solo se definen las cuentas al DEBE y las cuentas al HABER y se les asigna un nombre de plantilla.

Cuando el usuario final quiere crear un nuevo comprobante lo puede hacer a partir de una plantilla, donde se recupera todas las cuentas contables y solo se completan los importes; las cuentas que no tienen importes las eliminan manualmente.

TAmbién es posible clonar un comprobante.

Incorporando estas funcionalidades en el sistema de contabilidad facilitariamos la elaboración de comprobantes manuales.

**Comment by rensi4rn** [comment]
Ya tenemos esta funcionalidad y aun mejor

![image](https://cloud.githubusercontent.com/assets/2071383/15753307/5e826e44-28c0-11e6-8497-8b6f5ba720cd.png),

se parametrizan las planitllas que inlcusive sirven de reportes   y 
calculan  los montos en función  a formulas  (se puede dejar los montos en cero si no quieres usar formulas)


![image](https://cloud.githubusercontent.com/assets/2071383/15753340/890951d2-28c0-11e6-9a73-ab224f68cee3.png)
