### ISSUE TITLE
ordenar los registros contables respetando orden de introducción

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#25]
ordenar los registros contables respetando orden de introducción

![image](https://cloud.githubusercontent.com/assets/19177149/17375333/79f915da-597e-11e6-8a44-d3780f44329e.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/18151686/ebfcdddc-6fbe-11e6-835c-4b025e9be77c.png)

Se aumenta la columna orden en la tabla transaccion y se modifico la consulta del reporte
