### ISSUE TITLE
OBS. Crear la opción GESTION  

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#26]
![image](https://cloud.githubusercontent.com/assets/19177149/17415895/b6e8f10a-5a59-11e6-947c-1cc65fa86965.png)

**Comment by rensi4rn** [comment]
Se aumentaron filtros de gestión y de tipo de comprobante
![image](https://cloud.githubusercontent.com/assets/2071383/21275234/235c00fa-c3a2-11e6-86e6-81c8b1b0e016.png)
