### ISSUE TITLE
El cpbte debe sub totalizar e enumerar paginas cuando son varias

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#28]
![image](https://cloud.githubusercontent.com/assets/19177149/17416187/08840d3c-5a5b-11e6-9667-ff58bd94f721.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/18150063/4030d7ee-6fb2-11e6-8c06-c4f36e818aaa.png)
