### ISSUE TITLE
Detectar facilmente las transacciones

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#29]
![image](https://cloud.githubusercontent.com/assets/19177149/17416820/fe2f25f8-5a5d-11e6-8dc3-f8bd008d519a.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/18134249/c693e6a6-6f6b-11e6-9884-2a5526844b0d.png)
