### ISSUE TITLE
Los Cpbtes de Ingreso y Egreso no comienzan del 1

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#30]
![image](https://cloud.githubusercontent.com/assets/19177149/17416960/c30711ce-5a5e-11e6-81e6-306eee3cf161.png)

**Comment by rensi4rn** [comment]
se corrigió el problema, con una variable en la clase de comprobante donde se indica si tiene que saltar o no la numeracion en caso de cbte de apertura

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/19579744/35540b88-96f0-11e6-8da3-1f8df33f77fe.png)
