### ISSUE TITLE
En Cpbte impreso solo en BS no debe aparecer perdida o ganancia por redondeo

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#31]
![image](https://cloud.githubusercontent.com/assets/19177149/17419492/aff5b614-5a6b-11e6-844c-7564b076d325.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/18149692/c2781f8a-6faf-11e6-8ac7-d59ea77db8a2.png)
soucionado
