### ISSUE TITLE
OBS. DEBE TENER LOS EE.FF. LA OPCION DE (CON MOVIMIENTO) (SIN MOVIMIENTO) PARA SU REPORTE

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#35]
![image](https://cloud.githubusercontent.com/assets/19177149/17500000/adae7562-5d9f-11e6-8fc0-e283c92c620a.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/18282951/36d0bf10-7431-11e6-9038-85ad681a6409.png)

![image](https://cloud.githubusercontent.com/assets/2071383/18282964/483bd726-7431-11e6-8bc8-fa1832723661.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/18283497/83cf7d5e-7433-11e6-83bc-cd26da318bd0.png)
