### ISSUE TITLE
no coinciden los datos automáticos en ventas

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#40]
![image](https://cloud.githubusercontent.com/assets/19177149/17825017/5112895a-6633-11e6-9063-5bcaec75a6b3.png)

**Comment by rensi4rn** [comment]
se detecto que este problema pasa cuando:   primero se selecciona un nro de autorización que existe y se cargan los datos dependientes (NIT y nombre),....  y después se edita la autorización pero no existe el nro registrado, entonces no se resetea el anterior nit y nombre, o cual genera esta confusión

**Comment by rensi4rn** [comment]
cuando no se tiene el valor ahora reseta el nit y el nombre
