### ISSUE TITLE
codificación editable del plan de cuentas

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#42]
![image](https://cloud.githubusercontent.com/assets/19177149/18103976/f132af46-6ec6-11e6-9b25-7047c8f7f8d5.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/18150655/9f473666-6fb6-11e6-98a5-c546f91c97cd.png)


se abrio el campo para permitir ajustes
