### ISSUE TITLE
REPITE CODIGOS AL INTRODUCIR PLAN DE CUENTAS

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#43]
![image](https://cloud.githubusercontent.com/assets/19177149/18137634/2e71f3d4-6f77-11e6-8f40-66283b37b0d5.png)

**Comment by rensi4rn** [comment]
![Uploading image.png…]()

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/18150637/7618e8c0-6fb6-11e6-86bc-0c25a8de6b89.png)
