### ISSUE TITLE
Considerar estas adiciones

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#44]
![image](https://cloud.githubusercontent.com/assets/19177149/18280075/d4e9ba82-7425-11e6-8422-18e342886c99.png)

**Comment by rensi4rn** [comment]
En la definición de la relación contable se configura si la misma va tener, partidas, auxiliares y sus tipo de flujo gasto o recurso, se hace según el análisis de la transacción contable donde será utilizada
