### ISSUE TITLE
Considerar cambio en tipos de documento en registro de compras

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#45]
![image](https://cloud.githubusercontent.com/assets/19177149/18315784/3a6b277c-74e6-11e6-9bc6-b045fa01028b.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/19706114/396678fe-9ade-11e6-88b2-0219a7cdd1f6.png)

Esto es solo cuestion de entrar a la opción de plantillas (en el sistema de parámetros generales > otros) y editar el nombre de cada plantilla según el gusto del usuario
