### ISSUE TITLE
Considerar estas opciones en OT

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#46]
![image](https://cloud.githubusercontent.com/assets/19177149/18320920/db8fcca8-74f9-11e6-89bf-fc48510e5622.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/19706030/c2aef16e-9add-11e6-96b7-d05217434195.png)

por defecto todo concepto de gasto nuevo tiene las OT configuradas como opcionales con el filtro de OT marcados como todos
