### ISSUE TITLE
Considerar esta solicitud que facilita y ahorra trabajo en la elaboración de EEFF y otros papeles de trabajo

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#47]
![image](https://cloud.githubusercontent.com/assets/19177149/18388974/b797a8ba-7671-11e6-9d53-6b11c4f96772.png)

**Comment by rensi4rn** [comment]
para introducir varias cuentas de una vez tenemos la opción de origen detalle donde se especificar la cuenta del mayor y el nivel de anidamiento que  necesite.
Por otros lado  cada planilla significa una sola columna de datos , para hacer un reporte como la hoja de trabajo se necesitan ocupar varias plantillas y agruparla con la opción de dependencias, (cada plantilla significara una columna de la hoja de trabajo)
