### ISSUE TITLE
Corregir esta observación

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#49]
![image](https://cloud.githubusercontent.com/assets/19177149/18457319/b32e5ee8-7925-11e6-8f92-afb3f2bbb184.png)

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/19580661/b84d06e8-96f5-11e6-8109-99f99d826df7.png)

solucionado
