### ISSUE TITLE
Verificar la generación de comprobante mensual

### ISSUE THREAD

**Issue by ernesto37** [kplian/sis_contabilidad#50]
![image](https://cloud.githubusercontent.com/assets/19177149/18636216/02c79c28-7e56-11e6-995a-ee4a7bedd21b.png)

**Comment by rensi4rn** [comment]
este problema por los códigos configurados en la la clases de comprobante y  los configurados en la plantilla de comprobante, en la plantilla de cbte debe hacerse referencia a un código de clase de cbte existente
